### ISSUE TITLE
如果“全屏” 两个字可以换成 图标 

### ISSUE THREAD

**Issue by ooing** [chris-peng/wangEditor-fullscreen-plugin#2]
会和 编辑器本身更和谐

**Comment by LianGee** [comment]
> editor.create();
const toolBar = document.getElementsByClassName('w-e-toolbar').item(0);
const editIcon = document.getElementById('icon');
if (toolBar && editIcon) {
    editIcon.style.display = 'block';
    toolBar.append(editIcon);
}

可以自己写个Icon 放在div上，然后插进去...
![image](https://user-images.githubusercontent.com/3133666/68156782-69128500-ff87-11e9-8a50-9171580c6695.png)
